# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 16:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maindb',
            old_name='url',
            new_name='urls_db',
        ),
    ]
