# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='defaultDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_no', models.IntegerField(default='')),
                ('address', models.URLField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='MainDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_no', models.IntegerField(default='')),
                ('address', models.URLField(max_length=300)),
                ('auto_date', models.DateTimeField(auto_now_add=True)),
                ('timeA', models.TimeField()),
                ('timeB', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='userDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='maindb',
            name='user_sno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UI.userDB'),
        ),
    ]
