# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 08:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maindb',
            name='user_sno',
        ),
        migrations.DeleteModel(
            name='userDB',
        ),
    ]
