# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0002_auto_20170317_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maindb',
            name='auto_date',
            field=models.DateTimeField(),
        ),
    ]
